# Generated by Django 3.1 on 2021-05-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='append_file',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tools.files'),
            preserve_default=False,
        ),
    ]
