# Generated by Django 3.1 on 2021-05-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_append_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='append_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
