# Generated by Django 3.1 on 2021-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210504_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
