# Generated by Django 3.1 on 2021-05-02 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('hits', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('share', models.BooleanField(default=True)),
                ('abstract', models.CharField(default='暂无简介，进来看看吧', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
