# Generated by Django 3.1 on 2021-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
