# Generated by Django 3.0 on 2021-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('level', models.IntegerField(choices=[(0, '黑名单用户'), (1, '普通用户'), (2, '认证用户'), (3, '超级用户'), (4, '管理员')], default=1)),
            ],
        ),
    ]
