# Generated by Django 3.0 on 2021-04-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headermenu',
            options={'ordering': ['orderkey']},
        ),
        migrations.AddField(
            model_name='headermenu',
            name='orderkey',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
