# Generated by Django 3.0 on 2021-04-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210406_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headermenu',
            name='level',
            field=models.IntegerField(default='012345'),
        ),
    ]
