# Generated by Django 3.1 on 2021-04-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210406_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='headermenu',
            name='url',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
