# Generated by Django 3.1 on 2021-05-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_headermenu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headermenu',
            name='level',
            field=models.CharField(default='012345', max_length=10),
        ),
    ]
