# Generated by Django 3.0 on 2021-04-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registercodesaver',
            name='user',
        ),
        migrations.AddField(
            model_name='registercodesaver',
            name='telphone',
            field=models.CharField(default='0000000', max_length=11),
            preserve_default=False,
        ),
    ]
