# Generated by Django 3.1 on 2021-05-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210421_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registercodesaver',
            old_name='telphone',
            new_name='telephone',
        ),
    ]
