# Generated by Django 3.1 on 2021-05-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210501_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='telphone',
            new_name='telephone',
        ),
    ]
