# Generated by Django 3.1 on 2021-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='url',
            field=models.CharField(default='url', max_length=10),
            preserve_default=False,
        ),
    ]
